import { StyleSheet } from "react-native";

const styles = StyleSheet.create({

    container: {
      flex: 1,
    },
    map: {
      flex: 1,
    },
    searchContainer: {
      position: "absolute",
      top: 10,
      left: 10,
      right: 10,
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: "#fff",
      borderRadius: 25,
      paddingHorizontal: 10,
      elevation: 5,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
    },
    searchInput: {
      flex: 1,
      height: 40,
      fontSize: 16,
      color: "#333",
    },
    searchImageContainer: {
      padding: 5,
    },
    photoOverlayContent: {
      width: "75%",
      height: "50%",
      borderRadius: 20,
      padding: 20,
      alignItems: "center",
      justifyContent: "space-around",
    },
    overlayButton: {
      backgroundColor: "#007AFF",
      paddingVertical: 10,
      paddingHorizontal: 20,
      borderRadius: 20,
      marginVertical: 10,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      elevation: 5,
    },
    assistantButton: {
      position: "absolute",
      top: 60,
      right: 10,
      backgroundColor: "#FF9500",
      paddingVertical: 10,
      paddingHorizontal: 15,
      borderRadius: 20,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      elevation: 5,
    },
    routeWiseButton: {
      position: "absolute",
      top: 60,
      left: 10,
      backgroundColor: "#007AFF",
      paddingVertical: 10,
      paddingHorizontal: 20,
      borderRadius: 20,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      elevation: 5,
    },
    routeWiseOverlay: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: "rgba(0, 0, 0, 0.3)",
      justifyContent: "flex-start",
      paddingTop: 100,
      alignItems: "center",
    },
    inputContainer: {
      width: "90%",
      backgroundColor: "#fff",
      borderRadius: 20,
      padding: 20,
      elevation: 5,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
    },
    inputWrapper: {
      borderRadius: 25,
      marginBottom: 10,
      overflow: "hidden",
      elevation: 5,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
    },
    beautifiedInput: {
      height: 50,
      paddingHorizontal: 20,
      fontSize: 16,
      color: "#ffffff",
      backgroundColor: "rgba(0, 0, 0, 0.1)",
      borderRadius: 25,
    },
    cancelIcon: {
      position: "absolute",
      top: 20,
      right: 20,
      zIndex: 1,
    },
    bottomContainer: {
      position: "absolute",
      bottom: 120,
      left: 10,
      right: 10,
      alignItems: "center",
      backgroundColor: "transparent",
      padding: 10,
      borderRadius: 10,
      minHeight: 80,
      maxHeight: 150,
    },
    buttonRow: {
      flexDirection: "row",
      justifyContent: "space-around",
      width: "100%",
      marginVertical: 10,
      flexWrap: "wrap",
    },
    functionButton: {
      backgroundColor: "#007AFF",
      paddingVertical: 8,
      paddingHorizontal: 15,
      borderRadius: 20,
      margin: 5,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      elevation: 5,
    },
    travelTimesPanel: {
      width: "100%",
      alignItems: "center",
      backgroundColor: "rgba(255, 255, 255, 0.9)",
      padding: 10,
      borderRadius: 10,
    },
    timeRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      width: "100%",
      marginBottom: 10,
      flexWrap: "wrap",
    },
    timeList: {
      maxHeight: 80,
      width: "100%",
      marginBottom: 10,
    },
    timeTitle: {
      fontWeight: "bold",
      fontSize: 16,
      marginBottom: 5,
    },
    timeText: {
      fontSize: 14,
      color: "#333",
      marginVertical: 2,
    },
    panel: {
      position: "absolute",
      bottom: 0,
      left: 0,
      right: 0,
      backgroundColor: "#fff",
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      elevation: 5,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: -2 },
      shadowOpacity: 0.3,
      overflow: "hidden",
    },
    panelHandle: {
      width: 40,
      height: 5,
      backgroundColor: "#ccc",
      borderRadius: 2.5,
      alignSelf: "center",
      marginTop: 10,
    },
    panelContent: {
      padding: 15,
      paddingBottom: 80,
    },
    panelTitle: {
      fontSize: 18,
      fontWeight: "bold",
      marginBottom: 10,
    },
    panelText: {
      fontSize: 14,
      color: "#333",
      marginBottom: 10,
    },
    panelSpacer: {
      height: 20,
    },
    floatingButtons: {
      flexDirection: "row",
      justifyContent: "space-around",
      paddingVertical: 10,
      position: "absolute",
      bottom: 0,
      left: 0,
      right: 0,
      backgroundColor: "#fff",
    },
    floatingButton: {
      backgroundColor: "#007AFF",
      paddingVertical: 10,
      paddingHorizontal: 15,
      borderRadius: 20,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      elevation: 5,
    },
    buttonText: {
      color: "white",
      fontWeight: "bold",
    },
    callout: {
      width: 200,
      padding: 10,
      backgroundColor: "rgba(255, 255, 255, 0.9)",
      borderRadius: 10,
      borderWidth: 1,
      borderColor: "#ccc",
    },
    calloutTitle: {
      fontWeight: "bold",
      fontSize: 16,
      marginBottom: 5,
    },
    calloutDescription: {
      fontSize: 12,
      color: "#333",
      marginBottom: 5,
      minHeight: 40,
    },
    timeButtonRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      marginTop: 10,
      flexWrap: "wrap",
    },
    timeButton: {
      backgroundColor: "#FF9500",
      paddingVertical: 8,
      paddingHorizontal: 10,
      borderRadius: 20,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      elevation: 5,
      margin: 2,
    },
    navigateButton: {
      backgroundColor: "#007AFF",
      paddingVertical: 10,
      paddingHorizontal: 20,
      borderRadius: 20,
      marginTop: 10,
      alignSelf: "center",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      elevation: 5,
    },
    overlay: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: "rgba(0, 0, 0, 0.5)",
      justifyContent: "center",
      alignItems: "center",
    },
    overlayContent: {
      width: 280,
      height: 280,
      borderRadius: 20,
      alignItems: "center",
      justifyContent: "space-around",
      padding: 20,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 5 },
      shadowOpacity: 0.3,
      elevation: 10,
    },
    syncContainer: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 10,
    },
    syncLabel: {
      fontSize: 18,
      fontWeight: "600",
      color: "#fff",
      marginRight: 10,
    },
    syncStatus: {
      fontSize: 18,
      fontWeight: "600",
      color: "#fff",
    },
    generateButton: {
      backgroundColor: "#007AFF",
      paddingVertical: 12,
      paddingHorizontal: 30,
      borderRadius: 25,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      elevation: 5,
    },
    generateButtonText: {
      color: "white",
      fontSize: 16,
      fontWeight: "bold",
    },
    codeContainer: {
      marginTop: 20,
      alignItems: "center",
      marginBottom: 100,
    },
    generatedCodeText: {
      fontSize: 24,
      fontWeight: "bold",
      color: "#000",
      backgroundColor: "rgba(255, 255, 255, 0.8)",
      padding: 15,
      borderRadius: 15,
      textAlign: "center",
      width: 120,
    },
    closeButton: {
      backgroundColor: "#FF2D55",
      paddingVertical: 10,
      paddingHorizontal: 20,
      borderRadius: 25,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      elevation: 5,
      position: "absolute",
      bottom: 20,
    },
    closeButtonText: {
      color: "#fff",
      fontSize: 16,
      fontWeight: "bold",
    },
    searchOverlay: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: "rgba(0, 0, 0, 0.5)",
      justifyContent: "center",
      alignItems: "center",
    },
    searchOverlayContent: {
      width: "75%",
      height: "75%",
      borderRadius: 20,
      padding: 20,
      alignItems: "center",
      justifyContent: "space-around",
    },
    overlayTitle: {
      fontSize: 24,
      fontWeight: "bold",
      color: "#fff",
      marginBottom: 20,
    },
    overlayText: {
      fontSize: 16,
      color: "#fff",
      textAlign: "center",
    },
  
    panelSubtitle: {
      fontSize: 14,
      color: "#666",
      marginBottom: 15,
    },
    section: {
      marginBottom: 20,
    },
    sectionTitle: {
      fontSize: 16,
      fontWeight: "bold",
      color: "#333",
      marginBottom: 8,
    },
    sectionDescription: {
      fontSize: 12,
      color: "#666",
      marginBottom: 10,
    },
    buttonContainer: {
      flexDirection: "row",
      justifyContent: "space-between",
    },
    actionButton: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: "#007AFF",
      paddingVertical: 10,
      paddingHorizontal: 15,
      borderRadius: 10,
      marginHorizontal: 5,
      marginBottom: 10,
    },
    actionButtonText: {
      color: "#fff",
      fontSize: 14,
      fontWeight: "600",
      marginLeft: 8,
    },
    timeButtonContainer: {
      flexDirection: "row",
      justifyContent: "space-between",
      marginBottom: 10,
    },
    // timeButton: {
    //   flex: 1,
    //   backgroundColor: "#f0f0f0",
    //   paddingVertical: 8,
    //   paddingHorizontal: 10,
    //   borderRadius: 10,
    //   marginHorizontal: 5,
    //   alignItems: "center",
    // },
    timeButtonActive: {
      backgroundColor: "#007AFF",
    },
    timeButtonText: {
      fontSize: 12,
      color: "#333",
    },
    timeButtonTextActive: {
      color: "#fff",
    },
    shuttleInfo: {
      backgroundColor: "#f0f0f0",
      padding: 10,
      borderRadius: 10,
      marginTop: 10,
    },
    shuttleInfoText: {
      fontSize: 14,
      color: "#333",
      marginVertical: 2,
    },
    horizontalScroll: {
      flexDirection: "row",
      marginVertical: 10,
    },
    placeCard: {
      backgroundColor: "#f0f0f0",
      paddingVertical: 10,
      paddingHorizontal: 15,
      borderRadius: 10,
      marginRight: 10,
    },
    placeCardText: {
      fontSize: 14,
      color: "#333",
      fontWeight: "600",
    },
  });


  export default styles; // Use default export
  