// // import { StyleSheet } from "react-native";

// // const styles = StyleSheet.create({
// //   container: {
// //     flex: 1,
// //   },
// //   map: {
// //     flex: 1,
// //   },
// //   searchContainer: {
// //     position: "absolute",
// //     top: 10,
// //     left: 10,
// //     right: 10,
// //     flexDirection: "row",
// //     alignItems: "center",
// //     backgroundColor: "#fff",
// //     borderRadius: 25,
// //     paddingHorizontal: 10,
// //     elevation: 5,
// //     shadowColor: "#000",
// //     shadowOffset: { width: 0, height: 2 },
// //     shadowOpacity: 0.3,
// //   },
// //   searchInput: {
// //     flex: 1,
// //     height: 50,
// //     fontSize: 16,
// //     color: "#333",
// //     paddingHorizontal: 10,
// //   },
// //   searchImageContainer: {
// //     padding: 10,
// //   },
// //   photoIconContainer: {
// //     padding: 10,
// //   },
// //   routeWiseButton: {
// //     position: "absolute",
// //     left: 10,
// //     backgroundColor: "#007AFF",
// //     paddingVertical: 10,
// //     paddingHorizontal: 20,
// //     borderRadius: 20,
// //     shadowColor: "#000",
// //     shadowOffset: { width: 0, height: 2 },
// //     shadowOpacity: 0.3,
// //     elevation: 5,
// //   },
// //   routeWiseOverlay: {
// //     position: "absolute",
// //     left: 10,
// //     right: 10,
// //     backgroundColor: "transparent",
// //   },
// // cancelIcon: {
// //   position: "absolute",
// //   top: 10,
// //   right: 10,
// //   zIndex: 600, // Higher than overlay but lower than active routeWiseButton
// // },
// //   inputContainer: {
// //     backgroundColor: "rgba(255, 255, 255, 0.9)",
// //     padding: 15,
// //     borderRadius: 10,
// //     elevation: 5,
// //   },
// //   inputWrapper: {
// //     borderRadius: 25,
// //     marginBottom: 10,
// //     overflow: "hidden",
// //     elevation: 5,
// //     shadowColor: "#000",
// //     shadowOffset: { width: 0, height: 2 },
// //     shadowOpacity: 0.3,
// //   },
// //   beautifiedInput: {
// //     height: 50,
// //     paddingHorizontal: 20,
// //     fontSize: 16,
// //     color: "#ffffff",
// //     backgroundColor: "rgba(0, 0, 0, 0.1)",
// //     borderRadius: 25,
// //   },
// //   buttonRow: {
// //     flexDirection: "row",
// //     justifyContent: "space-between",
// //     marginTop: 10,
// //   },
// //   functionButton: {
// //     backgroundColor: "#007AFF",
// //     paddingVertical: 10,
// //     paddingHorizontal: 15,
// //     borderRadius: 20,
// //     flex: 1,
// //     marginHorizontal: 5,
// //     alignItems: "center",
// //   },
// //   bottomContainer: {
// //     position: "absolute",
// //     bottom: 80,
// //     left: 10,
// //     right: 10,
// //     alignItems: "center",
// //     backgroundColor: "rgba(255, 255, 255, 0.9)",
// //     padding: 10,
// //     borderRadius: 10,
// //   },
// //   travelTimesPanel: {
// //     width: "100%",
// //     alignItems: "center",
// //   },
// //   timeRow: {
// //     flexDirection: "row",
// //     justifyContent: "space-between",
// //     width: "100%",
// //     marginBottom: 10,
// //   },
// //   timeList: {
// //     maxHeight: 150,
// //     width: "100%",
// //   },
// //   timeTitle: {
// //     fontWeight: "bold",
// //     marginBottom: 5,
// //     fontSize: 16,
// //   },
// //   timeText: {
// //     marginHorizontal: 5,
// //     fontSize: 14,
// //     marginVertical: 2,
// //   },
// //   floatingButtons: {
// //     position: "absolute",
// //     bottom: 20,
// //     left: 20,
// //     right: 20,
// //     flexDirection: "row",
// //     justifyContent: "space-around",
// //   },
// //   floatingButton: {
// //     backgroundColor: "#007AFF",
// //     paddingVertical: 10,
// //     paddingHorizontal: 15,
// //     borderRadius: 20,
// //     shadowColor: "#000",
// //     shadowOffset: { width: 0, height: 2 },
// //     shadowOpacity: 0.3,
// //     elevation: 5,
// //   },
// //   topRightButton: {
// //     position: "absolute",
// //     right: 10,
// //     backgroundColor: "#FF9500",
// //     paddingVertical: 10,
// //     paddingHorizontal: 15,
// //     borderRadius: 20,
// //     shadowColor: "#000",
// //     shadowOffset: { width: 0, height: 2 },
// //     shadowOpacity: 0.3,
// //     elevation: 5,
// //   },
// //   buttonText: {
// //     color: "white",
// //     fontWeight: "bold",
// //   },
// //   callout: {
// //     width: 200,
// //     padding: 10,
// //     backgroundColor: "rgba(255, 255, 255, 0.9)",
// //     borderRadius: 10,
// //   },
// //   calloutTitle: {
// //     fontWeight: "bold",
// //     fontSize: 16,
// //     marginBottom: 5,
// //   },
// //   calloutDescription: {
// //     fontSize: 12,
// //     color: "#333",
// //   },
// //   overlay: {
// //     position: "absolute",
// //     top: 0,
// //     bottom: 0,
// //     left: 0,
// //     right: 0,
// //     backgroundColor: "rgba(0, 0, 0, 0.5)",
// //     justifyContent: "center",
// //     alignItems: "center",
// //   },
// //   photoOverlayContent: {
// //     width: "80%",
// //     padding: 20,
// //     borderRadius: 10,
// //     alignItems: "center",
// //   },
// //   overlayTitle: {
// //     fontSize: 20,
// //     fontWeight: "bold",
// //     color: "#fff",
// //     marginBottom: 10,
// //   },
// //   overlayText: {
// //     fontSize: 16,
// //     color: "#fff",
// //     marginBottom: 20,
// //     textAlign: "center",
// //   },
// //   overlayButton: {
// //     backgroundColor: "#007AFF",
// //     paddingVertical: 10,
// //     paddingHorizontal: 20,
// //     borderRadius: 20,
// //     marginBottom: 10,
// //     width: "100%",
// //     alignItems: "center",
// //   },
// //   closeButton: {
// //     marginTop: 10,
// //     padding: 10,
// //   },
// //   closeButtonText: {
// //     color: "#fff",
// //     fontSize: 16,
// //     fontWeight: "bold",
// //   },
// // });

// // export default styles;


// import { StyleSheet } from "react-native";

// const styles = StyleSheet.create({
//   container: {
//     flex: 1,
//   },
//   map: {
//     flex: 1,
//   },
//   searchContainer: {
//     position: "absolute",
//     top: 10,
//     left: 10,
//     right: 10,
//     flexDirection: "row",
//     alignItems: "center",
//     backgroundColor: "#fff",
//     borderRadius: 25,
//     paddingHorizontal: 10,
//     elevation: 5,
//     shadowColor: "#000",
//     shadowOffset: { width: 0, height: 2 },
//     shadowOpacity: 0.3,
//   },
//   searchInput: {
//     flex: 1,
//     height: 50,
//     fontSize: 16,
//     color: "#333",
//     paddingHorizontal: 10,
//   },
//   searchImageContainer: {
//     padding: 10,
//   },
//   photoIconContainer: {
//     padding: 10,
//   },
//   routeWiseButton: {
//     position: "absolute",
//     left: 10,
//     backgroundColor: "#007AFF",
//     paddingVertical: 10,
//     paddingHorizontal: 20,
//     borderRadius: 20,
//     shadowColor: "#000",
//     shadowOffset: { width: 0, height: 2 },
//     shadowOpacity: 0.3,
//     elevation: 5,
//   },
//   routeWiseOverlay: {
//     position: "absolute",
//     left: 10,
//     right: 10,
//     backgroundColor: "transparent",
//   },
//   cancelIcon: {
//     position: "absolute",
//     top: 10,
//     right: 10,
//     zIndex: 600, // Higher than overlay but lower than active routeWiseButton
//   },
//   inputContainer: {
//     backgroundColor: "rgba(255, 255, 255, 0.9)",
//     padding: 15,
//     borderRadius: 10,
//     elevation: 5,
//   },
//   inputWrapper: {
//     borderRadius: 25,
//     marginBottom: 10,
//     overflow: "hidden",
//     elevation: 5,
//     shadowColor: "#000",
//     shadowOffset: { width: 0, height: 2 },
//     shadowOpacity: 0.3,
//   },
//   beautifiedInput: {
//     height: 50,
//     paddingHorizontal: 20,
//     fontSize: 16,
//     color: "#ffffff",
//     backgroundColor: "rgba(0, 0, 0, 0.1)",
//     borderRadius: 25,
//   },
//   buttonRow: {
//     flexDirection: "row",
//     justifyContent: "space-between",
//     marginTop: 10,
//   },
//   functionButton: {
//     backgroundColor: "#007AFF",
//     paddingVertical: 10,
//     paddingHorizontal: 15,
//     borderRadius: 20,
//     flex: 1,
//     marginHorizontal: 5,
//     alignItems: "center",
//   },
//   bottomContainer: {
//     position: "absolute",
//     bottom: 80,
//     left: 10,
//     right: 10,
//     alignItems: "center",
//     backgroundColor: "rgba(255, 255, 255, 0.9)",
//     padding: 10,
//     borderRadius: 10,
//   },
//   travelTimesPanel: {
//     width: "100%",
//     alignItems: "center",
//   },
//   timeRow: {
//     flexDirection: "row",
//     justifyContent: "space-between",
//     width: "100%",
//     marginBottom: 10,
//   },
//   timeList: {
//     maxHeight: 150,
//     width: "100%",
//   },
//   timeTitle: {
//     fontWeight: "bold",
//     marginBottom: 5,
//     fontSize: 16,
//   },
//   timeText: {
//     marginHorizontal: 5,
//     fontSize: 14,
//     marginVertical: 2,
//   },
//   floatingButtons: {
//     position: "absolute",
//     bottom: 20,
//     left: 20,
//     right: 20,
//     flexDirection: "row",
//     justifyContent: "space-around",
//   },
//   floatingButton: {
//     backgroundColor: "#007AFF",
//     paddingVertical: 10,
//     paddingHorizontal: 15,
//     borderRadius: 20,
//     shadowColor: "#000",
//     shadowOffset: { width: 0, height: 2 },
//     shadowOpacity: 0.3,
//     elevation: 5,
//   },
//   topRightButton: {
//     position: "absolute",
//     right: 10,
//     backgroundColor: "#FF9500",
//     paddingVertical: 10,
//     paddingHorizontal: 15,
//     borderRadius: 20,
//     shadowColor: "#000",
//     shadowOffset: { width: 0, height: 2 },
//     shadowOpacity: 0.3,
//     elevation: 5,
//   },
//   buttonText: {
//     color: "white",
//     fontWeight: "bold",
//   },
//   callout: {
//     width: 200,
//     padding: 10,
//     backgroundColor: "rgba(255, 255, 255, 0.9)",
//     borderRadius: 10,
//   },
//   calloutTitle: {
//     fontWeight: "bold",
//     fontSize: 16,
//     marginBottom: 5,
//   },
//   calloutDescription: {
//     fontSize: 12,
//     color: "#333",
//   },
//   overlay: {
//     position: "absolute",
//     top: 0,
//     bottom: 0,
//     left: 0,
//     right: 0,
//     backgroundColor: "rgba(0, 0, 0, 0.5)",
//     justifyContent: "center",
//     alignItems: "center",
//   },
//   photoOverlayContent: {
//     width: "80%",
//     padding: 20,
//     borderRadius: 10,
//     alignItems: "center",
//   },
//   overlayTitle: {
//     fontSize: 20,
//     fontWeight: "bold",
//     color: "#fff",
//     marginBottom: 10,
//   },
//   overlayText: {
//     fontSize: 16,
//     color: "#fff",
//     marginBottom: 20,
//     textAlign: "center",
//   },
//   overlayButton: {
//     backgroundColor: "#007AFF",
//     paddingVertical: 10,
//     paddingHorizontal: 20,
//     borderRadius: 20,
//     marginBottom: 10,
//     width: "100%",
//     alignItems: "center",
//   },
//   closeButton: {
//     marginTop: 10,
//     padding: 10,
//   },
//   closeButtonText: {
//     color: "#fff",
//     fontSize: 16,
//     fontWeight: "bold",
//   },
// });

// export default styles;





import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  map: {
    flex: 1,
  },
  searchContainer: {
    position: "absolute",
    top: 10,
    left: 10,
    right: 10,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: 25,
    paddingHorizontal: 10,
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
  },
  searchInput: {
    flex: 1,
    height: 40,
    fontSize: 16,
    color: "#333",
  },
  searchImageContainer: {
    padding: 5,
  },
  buttonContainer: {
    position: "absolute",
    top: 60,
    left: 10,
    right: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  routeWiseButton: {
    flex: 0.48,
    backgroundColor: "#007AFF",
    paddingVertical: 12,
    paddingHorizontal: 15,
    borderRadius: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    elevation: 5,
  },
  routeTrackerButton: {
    flex: 0.48,
    backgroundColor: "#fff",
    paddingVertical: 12,
    paddingHorizontal: 15,
    borderRadius: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    elevation: 5,
  },
  buttonIcon: {
    marginRight: 8,
  },
  buttonText: {
    color: "white",
    fontWeight: "bold",
    fontSize: 16,
  },
  routeTrackerButtonText: {
    color: "#007AFF",
    fontWeight: "bold",
    fontSize: 16,
  },
  routeWiseOverlay: {
    position: "absolute",
    top: 60,
    left: 10,
    right: 10,
    backgroundColor: "transparent",
    alignItems: "center",
  },
  inputContainer: {
    width: "100%",
    backgroundColor: "transparent",
    padding: 15,
  },
  inputWrapper: {
    marginBottom: 10,
    backgroundColor: "#fff",
    borderRadius: 8,
    padding: 5,
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
  },
  locationInputContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  beautifiedInput: {
    flex: 1,
    height: 40,
    paddingHorizontal: 15,
    fontSize: 16,
    color: "#333",
    backgroundColor: "#f0f0f0",
    borderRadius: 8,
  },
  myLocationButton: {
    padding: 10,
    marginLeft: 5,
  },
  inputLabel: {
    fontSize: 14,
    color: "#333",
    marginBottom: 5,
  },
  modeButtonRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 10,
  },
  modeButton: {
    flex: 1,
    backgroundColor: "#fff",
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    marginHorizontal: 5,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
  },
  modeButtonActive: {
    backgroundColor: "#007AFF",
  },
  modeButtonText: {
    fontSize: 12,
    color: "#666",
    marginTop: 5,
  },
  modeButtonTextActive: {
    fontSize: 12,
    color: "#fff",
    marginTop: 5,
  },
  navigateButton: {
    width: "100%",
    backgroundColor: "#fff",
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    borderWidth: 1,
    borderColor: "#007AFF",
  },
  navigateButtonText: {
    color: "#007AFF",
    fontWeight: "500",
    fontSize: 16,
  },
  routeIcon: {
    marginRight: 8,
  },
  cancelIcon: {
    position: "absolute",
    top: 10,
    right: 10,
    zIndex: 1,
  },
  bottomContainer: {
    position: "absolute",
    bottom: 120,
    left: 10,
    right: 10,
    alignItems: "center",
    backgroundColor: "transparent",
    padding: 10,
    borderRadius: 10,
    minHeight: 80,
    maxHeight: 150,
  },
  travelTimesPanel: {
    width: "100%",
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.9)",
    padding: 10,
    borderRadius: 10,
  },
  timeRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    marginBottom: 10,
  },
  timeList: {
    maxHeight: 80,
    width: "100%",
    marginBottom: 10,
  },
  timeTitle: {
    fontWeight: "bold",
    fontSize: 16,
    marginBottom: 5,
  },
  timeText: {
    fontSize: 14,
    color: "#333",
    marginVertical: 2,
  },
  floatingButtons: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 10,
    paddingHorizontal: 5,
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "#fff",
  },
  floatingButton: {
    flex: 1,
    backgroundColor: "#007AFF",
    paddingVertical: 12,
    paddingHorizontal: 10,
    borderRadius: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginHorizontal: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    elevation: 5,
  },
  callout: {
    width: 200,
    padding: 10,
    backgroundColor: "rgba(255, 255, 255, 0.9)",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#ccc",
  },
  calloutTitle: {
    fontWeight: "bold",
    fontSize: 16,
    marginBottom: 5,
  },
  calloutDescription: {
    fontSize: 12,
    color: "#333",
    marginBottom: 5,
    minHeight: 40,
  },
});

export default styles;