// import { StyleSheet } from "react-native";

// // Styles remain unchanged
// const styles = StyleSheet.create({
//     container: {
//       flex: 1,
//     },
//     map: {
//       flex: 1,
//     },
//     inputContainer: {
//       position: "absolute",
//       top: 10,
//       left: 10,
//       right: 10,
//       padding: 10,
//     },
//     inputWrapper: {
//       flexDirection: "row",
//       alignItems: "center",
//       borderRadius: 25,
//       marginBottom: 10,
//       overflow: "hidden",
//       elevation: 5,
//       shadowColor: "#000",
//       shadowOffset: { width: 0, height: 2 },
//       shadowOpacity: 0.3,
//       shadowRadius: 5,
//     },
//     beautifiedInput: {
//       flex: 1,
//       height: 50,
//       paddingHorizontal: 20,
//       fontSize: 16,
//       color: "#ffffff",
//       backgroundColor: "rgba(0, 0, 0, 0.1)",
//       borderRadius: 25,
//     },
//     clearButton: {
//       padding: 10,
//     },
//     clearButtonText: {
//       color: "#ffffff",
//       fontWeight: "bold",
//       fontSize: 16,
//     },
//     searchButton: {
//       backgroundColor: "#007AFF",
//       paddingVertical: 12,
//       paddingHorizontal: 30,
//       borderRadius: 25,
//       alignItems: "center",
//       shadowColor: "#000",
//       shadowOffset: { width: 0, height: 2 },
//       shadowOpacity: 0.3,
//       shadowRadius: 4,
//       elevation: 5,
//       marginTop: 10,
//     },
//     searchButtonText: {
//       color: "#fff",
//       fontSize: 16,
//       fontWeight: "bold",
//     },
//     floatingButtons: {
//       position: "absolute",
//       bottom: 20,
//       left: 20,
//       right: 20,
//       flexDirection: "row",
//       justifyContent: "space-around",
//     },
//     floatingButton: {
//       backgroundColor: "#007AFF",
//       paddingVertical: 10,
//       paddingHorizontal: 15,
//       borderRadius: 20,
//       shadowColor: "#000",
//       shadowOffset: { width: 0, height: 2 },
//       shadowOpacity: 0.3,
//       elevation: 5,
//     },
//     buttonText: {
//       color: "white",
//       fontWeight: "bold",
//     },
//     studentInfoContainer: {
//       position: "absolute",
//       top: 10,
//       left: 10,
//       right: 10,
//       padding: 10,
//     },
//     studentCard: {
//       backgroundColor: "white",
//       borderRadius: 12,
//       padding: 15,
//       flexDirection: "row",
//       alignItems: "center",
//       elevation: 5,
//       shadowColor: "#000",
//       shadowOffset: { width: 0, height: 2 },
//       shadowOpacity: 0.3,
//       shadowRadius: 4,
//     },
//     studentInitial: {
//       width: 50,
//       height: 50,
//       backgroundColor: "#4facfe",
//       borderRadius: 25,
//       justifyContent: "center",
//       alignItems: "center",
//       marginRight: 15,
//     },
//     studentInitialText: {
//       color: "white",
//       fontSize: 24,
//       fontWeight: "bold",
//     },
//     studentDetails: {
//       flex: 1,
//     },
//     studentName: {
//       fontSize: 18,
//       fontWeight: "bold",
//       color: "#333",
//     },
//     studentSchool: {
//       fontSize: 14,
//       color: "#666",
//       marginTop: 2,
//     },
//     studentCode: {
//       fontSize: 14,
//       color: "#666",
//       marginTop: 2,
//     },
//     resetButton: {
//       backgroundColor: "#ff3b30",
//       paddingVertical: 8,
//       paddingHorizontal: 12,
//       borderRadius: 8,
//     },
//     resetButtonText: {
//       color: "white",
//       fontSize: 14,
//       fontWeight: "bold",
//     },
//     calloutTitle: {
//       fontWeight: "bold",
//       fontSize: 16,
//       marginBottom: 5,
//     },
//     statusOverlay: {
//       position: "absolute",
//       bottom: 80,
//       left: 10,
//       right: 10,
//       backgroundColor: "rgba(255, 255, 255, 0.9)",
//       padding: 10,
//       borderRadius: 10,
//       alignItems: "center",
//     },
//     statusText: {
//       fontSize: 16,
//       fontWeight: "bold",
//     },
//     routeButton: {
//       backgroundColor: "#007AFF",
//       paddingVertical: 10,
//       paddingHorizontal: 20,
//       borderRadius: 8,
//     },
//     routeButtonText: {
//       color: "white",
//       fontSize: 16,
//       fontWeight: "bold",
//     },
//   });

//   export default styles; // Use default export
  


import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },
  map: {
    flex: 1,
  },
  inputContainer: {
    position: "absolute",
    top: 10,
    left: 10,
    right: 10,
    backgroundColor: "transparent",
    padding: 10,
  },
  inputWrapper: {
    backgroundColor: "#fff",
    borderRadius: 8,
    padding: 5,
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    marginBottom: 10,
  },
  beautifiedInput: {
    flex: 1,
    height: 40,
    paddingHorizontal: 15,
    fontSize: 16,
    color: "#333",
    backgroundColor: "#f0f0f0",
    borderRadius: 8,
  },
  clearButton: {
    padding: 10,
    marginLeft: 5,
  },
  clearButtonText: {
    color: "#007AFF",
    fontWeight: "bold",
    fontSize: 16,
  },
  searchButton: {
    backgroundColor: "#007AFF",
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
  },
  searchButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },
  floatingButtons: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 10,
    paddingHorizontal: 5,
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "#fff",
  },
  floatingButton: {
    flex: 1,
    backgroundColor: "#007AFF",
    paddingVertical: 12,
    paddingHorizontal: 10,
    borderRadius: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginHorizontal: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    elevation: 5,
  },
  buttonText: {
    color: "white",
    fontWeight: "bold",
    fontSize: 16,
  },
  studentInfoContainer: {
    position: "absolute",
    top: 10,
    left: 10,
    right: 10,
    padding: 10,
  },
  studentCard: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 15,
    flexDirection: "row",
    alignItems: "center",
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
  },
  studentInitial: {
    width: 50,
    height: 50,
    backgroundColor: "#007AFF",
    borderRadius: 25,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 15,
  },
  studentInitialText: {
    color: "white",
    fontSize: 24,
    fontWeight: "bold",
  },
  studentDetails: {
    flex: 1,
  },
  studentName: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#333",
  },
  studentSchool: {
    fontSize: 14,
    color: "#666",
    marginTop: 2,
  },
  studentCode: {
    fontSize: 14,
    color: "#666",
    marginTop: 2,
  },
  studentStatus: {
    fontSize: 14,
    fontWeight: "bold",
    marginTop: 2,
  },
  resetButton: {
    backgroundColor: "#fff",
    borderColor: "#007AFF",
    borderWidth: 1,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
  },
  resetButtonText: {
    color: "#007AFF",
    fontSize: 14,
    fontWeight: "bold",
  },
  statusOverlay: {
    position: "absolute",
    bottom: 80,
    left: 10,
    right: 10,
    backgroundColor: "#fff",
    padding: 15,
    borderRadius: 10,
    alignItems: "center",
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
  },
  statusText: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#333",
  },
  destinationText: {
    fontSize: 14,
    color: "#666",
    marginBottom: 10,
    textAlign: "center",
  },
  etaText: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#007AFF",
  },
  routeButton: {
    backgroundColor: "#007AFF",
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    width: "100%",
    alignItems: "center",
  },
  routeButtonText: {
    color: "white",
    fontSize: 16,
    fontWeight: "bold",
  },
  calloutTitle: {
    fontWeight: "bold",
    fontSize: 16,
    marginBottom: 5,
    color: "#333",
  },
});

export default styles;